/**
 * Slug -> namn for alla 75 CV-exempel och 75 brev-exempel.
 * Genererad fran scripts/extract-yrken.mjs.
 */

export const CV_YRKEN: Record<string, string> = {
  underskoterska: 'Undersköterska',
  vardadministrator: 'Vårdadministratör',
  vardbitrade: 'Vårdbiträde',
  hemtjanst: 'Hemtjänst',
  forskollarare: 'Förskollärare',
  receptionist: 'Receptionist',
  ingenjor: 'Ingenjör',
  lagerarbetare: 'Lagerarbetare',
  administrator: 'Administratör',
  lokalvardare: 'Lokalvårdare',
  handlaggare: 'Handläggare',
  lakare: 'Läkare',
  butiksbitrade: 'Butiksbiträde',
  butikssaljare: 'Butikssäljare',
  saljare: 'Säljare',
  sommarjobb: 'Sommarjobb',
  'it-konsult': 'IT-konsult',
  student: 'Student',
  larare: 'Lärare',
  sjukskoterska: 'Sjuksköterska',
  specialistsjukskoterska: 'Specialistsjuksköterska',
  ekonomiassistent: 'Ekonomiassistent',
  enhetschef: 'Enhetschef',
  barnmorska: 'Barnmorska',
  barnskotare: 'Barnskötare',
  'personlig-assistent': 'Personlig assistent',
  'servitris-restaurangbitrade': 'Servitris och restaurangbiträde',
  kock: 'Kock',
  chef: 'Chef',
  produktchef: 'Produktchef',
  projektledare: 'Projektledare',
  elevassistent: 'Elevassistent',
  kundradgivare: 'Kundrådgivare',
  kundtjanst: 'Kundtjänst',
  kundtjanstmedarbetare: 'Kundtjänstmedarbetare',
  kurator: 'Kurator',
  grundskollarare: 'Grundskollärare',
  specialpedagog: 'Specialpedagog',
  fysioterapeut: 'Fysioterapeut',
  kontorsassistent: 'Kontorsassistent',
  automationsingenior: 'Automationsingenjör',
  konstruktor: 'Konstruktör',
  truckforare: 'Truckförare',
  logistiker: 'Logistiker',
  loneadministrator: 'Löneadministratör',
  lagerchef: 'Lagerchef',
  fastighetsskotare: 'Fastighetsskötare',
  hemtjanstpersonal: 'Hemtjänstpersonal',
  servicemedarbetare: 'Servicemedarbetare',
  socialsekreterare: 'Socialsekreterare',
  'hr-specialist': 'HR-specialist',
  controller: 'Controller',
  kassorska: 'Kassörska',
  butikschef: 'Butikschef',
  'account-manager': 'Account Manager',
  systemutvecklare: 'Systemutvecklare',
  'devops-engineer': 'DevOps Engineer',
  'projektledare-it': 'Projektledare IT',
  fritidspedagog: 'Fritidspedagog',
  redovisningsekonom: 'Redovisningsekonom',
  bartender: 'Bartender',
  konditor: 'Konditor',
  ekonom: 'Ekonom',
  'scrum-master': 'Scrum Master',
  teamledare: 'Teamledare',
  fritidsledare: 'Fritidsledare',
  psykolog: 'Psykolog',
  'lss-handlaggare': 'LSS-handläggare',
  hotellvard: 'Hotellvärd',
  'administrativ-assistent': 'Administrativ assistent',
  boendestod: 'Boendestöd',
  koksbitrade: 'Köksbiträde',
  barista: 'Barista',
  logistikassistent: 'Logistikassistent',
  terminalarbetare: 'Terminalarbetare',
  vaktmastare: 'Vaktmästare',
  socionom: 'Socionom',
  stodpedagog: 'Stödpedagog',
  chauffor: 'Chaufför',
  'it-tekniker': 'IT-tekniker',
  telefonforsaljare: 'Telefonförsäljare',
  diskare: 'Diskare',
  snickare: 'Snickare',
  elektriker: 'Elektriker',
  vaktare: 'Väktare',
  stadare: 'Städare',
}

export const BREV_YRKEN: Record<string, string> = {
  underskoterska: 'Undersköterska',
  student: 'Student',
  larare: 'Lärare',
  saljare: 'Säljare',
  sommarjobb: 'Sommarjobb',
  butikssaljare: 'Butikssäljare',
  sjukskoterska: 'Sjuksköterska',
  ekonomiassistent: 'Ekonomiassistent',
  barnskotare: 'Barnskötare',
  bartender: 'Bartender',
  'personlig-assistent': 'Personlig assistent',
  ingenjor: 'Ingenjör',
  forskollarare: 'Förskollärare',
  receptionist: 'Receptionist',
  lagerarbetare: 'Lagerarbetare',
  administrator: 'Administratör',
  lokalvardare: 'Lokalvårdare',
  handlaggare: 'Handläggare',
  lakare: 'Läkare',
  kurator: 'Kurator',
  butiksbitrade: 'Butiksbiträde',
  butikschef: 'Butikschef',
  'servitris-restaurangbitrade': 'Servitris och restaurangbiträde',
  chef: 'Chef',
  projektledare: 'Projektledare',
  'projektledare-it': 'Projektledare IT',
  elevassistent: 'Elevassistent',
  kundtjanst: 'Kundtjänst',
  stadare: 'Städare',
  vardbitrade: 'Vårdbiträde',
  hemtjanst: 'Hemtjänst',
  'it-konsult': 'IT-konsult',
  kassorska: 'Kassörska',
  kock: 'Kock',
  konditor: 'Konditor',
  specialpedagog: 'Specialpedagog',
  fysioterapeut: 'Fysioterapeut',
  fritidsledare: 'Fritidsledare',
  fritidspedagog: 'Fritidspedagog',
  redovisningsekonom: 'Redovisningsekonom',
  'hr-specialist': 'HR-specialist',
  systemutvecklare: 'Systemutvecklare',
  'account-manager': 'Account Manager',
  controller: 'Controller',
  'scrum-master': 'Scrum Master',
  truckforare: 'Truckförare',
  lagerchef: 'Lagerchef',
  barnmorska: 'Barnmorska',
  specialistsjukskoterska: 'Specialistsjuksköterska',
  loneadministrator: 'Löneadministratör',
  teamledare: 'Teamledare',
  enhetschef: 'Enhetschef',
  produktchef: 'Produktchef',
  boendestod: 'Boendestödjare',
  barista: 'Barista',
  koksbitrade: 'Köksbiträde',
  kontorsassistent: 'Kontorsassistent',
  konstruktor: 'Konstruktör',
  logistikassistent: 'Logistikassistent',
  'lss-handlaggare': 'LSS-handläggare',
  kundradgivare: 'Kundrådgivare',
  hotellvard: 'Hotellvärd',
  vardadministrator: 'Vårdadministratör',
  kundtjanstmedarbetare: 'Kundtjänstmedarbetare',
  terminalarbetare: 'Terminalarbetare',
  'administrativ-assistent': 'Administrativ assistent',
  grundskollarare: 'Grundskollärare',
  socialsekreterare: 'Socialsekreterare',
  ekonom: 'Ekonom',
  'devops-engineer': 'DevOps Engineer',
  psykolog: 'Psykolog',
  fastighetsskotare: 'Fastighetsskötare',
  hemtjanstpersonal: 'Hemtjänstpersonal',
  logistiker: 'Logistiker',
  servicemedarbetare: 'Servicemedarbetare',
  vaktmastare: 'Vaktmästare',
  socionom: 'Socionom',
  stodpedagog: 'Stödpedagog',
  chauffor: 'Chaufför',
  'it-tekniker': 'IT-tekniker',
  telefonforsaljare: 'Telefonförsäljare',
  diskare: 'Diskare',
  snickare: 'Snickare',
  elektriker: 'Elektriker',
  vaktare: 'Väktare',
}
