/**
 * Slug → yrkesnamn-mappning för dynamiska OG-bilder.
 *
 * Auto-genererad från exampleData i page.tsx. Hålls separat så
 * opengraph-image.tsx (edge runtime) inte behöver importera 10k+ rader data.
 *
 * Om du lägger till ett nytt yrke i page.tsx, lägg också till det här.
 */

export const SLUG_TO_YRKE: Record<string, string> = {
  hemtjanstpersonal: 'Hemtjänstpersonal',
  'personlig-assistent': 'Personlig assistent',
  barnskotare: 'Barnskötare',
  konditor: 'Konditor',
  specialpedagog: 'Specialpedagog',
  underskoterska: 'Undersköterska',
  'lss-handlaggare': 'LSS-handläggare',
  butikschef: 'Butikschef',
  lagerchef: 'Lagerchef',
  loneadministrator: 'Löneadministratör',
  servicemedarbetare: 'Servicemedarbetare',
  butikssaljare: 'Butikssäljare',
  'administrativ-assistent': 'Administrativ assistent',
  kock: 'Kock',
  'it-konsult': 'IT-konsult',
  logistiker: 'Logistiker',
  fysioterapeut: 'Fysioterapeut',
  larare: 'Lärare',
  handlaggare: 'Handläggare',
  elevassistent: 'Elevassistent',
  sjukskoterska: 'Sjuksköterska',
  administrator: 'Administratör',
  ingenjor: 'Ingenjör',
  psykolog: 'Psykolog',
  'projektledare-it': 'Projektledare IT',
  kundtjanst: 'Kundtjänst',
  forskollarare: 'Förskollärare',
  kundtjanstmedarbetare: 'Kundtjänstmedarbetare',
  receptionist: 'Receptionist',
  projektledare: 'Projektledare',
  butiksbitrade: 'Butiksbiträde',
  ekonom: 'Ekonom',
  fritidsledare: 'Fritidsledare',
  systemutvecklare: 'Systemutvecklare',
  socialsekreterare: 'Socialsekreterare',
  barnmorska: 'Barnmorska',
  'hr-specialist': 'HR-specialist',
  bartender: 'Bartender',
  grundskollarare: 'Grundskollärare',
  lokalvardare: 'Lokalvårdare',
  hemtjanst: 'Hemtjänst',
  sommarjobb: 'Sommarjobb',
  stadare: 'Städare',
  redovisningsekonom: 'Redovisningsekonom',
  saljare: 'Säljare',
  vardadministrator: 'Vårdadministratör',
  ekonomiassistent: 'Ekonomiassistent',
  kassorska: 'Kassörska',
  produktchef: 'Produktchef',
  'scrum-master': 'Scrum Master',
  fastighetsskotare: 'Fastighetsskötare',
  konstruktor: 'Konstruktör',
  'devops-engineer': 'DevOps Engineer',
  specialistsjukskoterska: 'Specialistsjuksköterska',
  boendestod: 'Boendestödjare',
  logistikassistent: 'Logistikassistent',
  kurator: 'Kurator',
  'account-manager': 'Account Manager',
  enhetschef: 'Enhetschef',
  lakare: 'Läkare',
  kundradgivare: 'Kundrådgivare',
  barista: 'Barista',
  hotellvard: 'Hotellvärd',
  teamledare: 'Teamledare',
  lagerarbetare: 'Lagerarbetare',
  truckforare: 'Truckförare',
  'servitris-restaurangbitrade': 'Servitris/Restaurangbiträde',
  chef: 'Chef',
  fritidspedagog: 'Fritidspedagog',
  student: 'Student',
  terminalarbetare: 'Terminalarbetare',
  controller: 'Controller',
  kontorsassistent: 'Kontorsassistent',
  koksbitrade: 'Köksbiträde',
  vardbitrade: 'Vårdbiträde',
  vaktmastare: 'Vaktmästare',
  socionom: 'Socionom',
  stodpedagog: 'Stödpedagog',
  chauffor: 'Chaufför',
}
